name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: Agent-1
    
    steps:  
      - name: checkout code 
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '23'
          
      - name: Frontend Compilation (syntax error)
        run: |
          cd client  
          find . -name "*.js" -exec node --check {} + 

      - name: Backend compilation (syntax error) 
        run: |
          cd api 
          find . -name "*.js" -exec node --check {} + 

  gitleaks-scan:
    runs-on: Agent-1
    steps: 
      - name: checkout code 
        uses: actions/checkout@v4
      
      - name: git leaks scans 
        uses: gitleaks/gitleaks-action@v2

      - name: gitleaks scan 
        run: | 
          git leaks detect --source ./client --exit-code 1
          git leaks detect --source ./api --exit-code 1 
        
      
         


        
    
        
